# Generated by Django 4.1.2 on 2022-10-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educenterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
    ]
